In [19]:
import pandas as pd 
from sklearn.model_selection import train_test_split

import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report

In [20]:
df = pd.read_csv(f'../data/train_feature.csv')

In [21]:
df.head()

,age,height(cm),weight(kg),waist(cm),bmi,eyesight(left),eyesight(right),is_blind_left,is_blind_right,systolic,...,Gtp,log_gtp,dental caries,Urine protein_1,Urine protein_2,Urine protein_3,Urine protein_4,Urine protein_5,Urine protein_6,smoking
0,55,165,60,81.0,22.038567,0.5,0.6,0,0,135,...,27,3.295837,0,1,0,0,0,0,0,1
1,70,165,65,89.0,23.875115,0.6,0.7,0,0,146,...,37,3.610918,1,1,0,0,0,0,0,0
2,20,170,75,81.0,25.951557,0.4,0.5,0,0,118,...,53,3.970292,0,1,0,0,0,0,0,1
3,35,180,95,105.0,29.320988,1.5,1.2,0,0,131,...,30,3.401197,1,1,0,0,0,0,0,0
4,30,165,60,80.5,22.038567,1.5,1.0,0,0,121,...,17,2.833213,0,1,0,0,0,0,0,1

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159251 entries, 0 to 159250
Data columns (total 35 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   age                                               159251 non-null  int64
 1   height(cm)                                        159251 non-null  int64
 2   weight(kg)                                        159251 non-null  int64
 3   waist(cm)                                         159251 non-null  float64
 4   bmi                                               159251 non-null  float64
 5   eyesight(left)                                    159251 non-null  float64
 6   eyesight(right)                                   159251 non-null  float64
 7   is_blind_left                                     159251 non-null  int64
 8   is_blind_right                                    159251 non-null  int64
 9   systolic                                          159251 non-null  int64
 10  relaxation                                        159251 non-null  int64
 11  blood_pressure_level_Elevated                     159251 non-null  int64
 12  blood_pressure_level_Normal                       159251 non-null  int64
 13  blood_pressure_level_Stage 1 High BP              159251 non-null  int64
 14  blood_pressure_level_Stage 2 High BP              159251 non-null  int64
 15  blood_pressure_level_Stage 3 High BP (Emergency)  159251 non-null  int64
 16  fasting blood sugar                               159251 non-null  int64
 17  Cholesterol                                       159251 non-null  int64
 18  triglyceride                                      159251 non-null  int64
 19  HDL                                               159251 non-null  int64
 20  LDL                                               159251 non-null  float64
 21  hemoglobin                                        159251 non-null  float64
 22  serum creatinine                                  159251 non-null  float64
 23  AST                                               159251 non-null  int64
 24  ALT                                               159251 non-null  int64
 25  Gtp                                               159251 non-null  int64
 26  log_gtp                                           159251 non-null  float64
 27  dental caries                                     159251 non-null  int64
 28  Urine protein_1                                   159251 non-null  int64
 29  Urine protein_2                                   159251 non-null  int64
 30  Urine protein_3                                   159251 non-null  int64
 31  Urine protein_4                                   159251 non-null  int64
 32  Urine protein_5                                   159251 non-null  int64
 33  Urine protein_6                                   159251 non-null  int64
 34  smoking                                           159251 non-null  int64
dtypes: float64(8), int64(27)
memory usage: 42.5 MB

In [23]:
X,y = df.iloc[:,:-1], df.iloc[:,-1]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size = 0.2, 
                                                    random_state=100,
                                                    stratify=y)

In [25]:
xg_clf = xgb.XGBClassifier(objective='binary:logistic', colsample_bytree=0.3, learning_rate=0.1,
                           max_depth=3, alpha=10, n_estimators=10)

In [26]:
# Fit the model to the training data
xg_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = xg_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Display classification report
print('\nClassification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.75

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.75      0.77     17920
           1       0.70      0.74      0.72     13931

    accuracy                           0.75     31851
   macro avg       0.74      0.75      0.74     31851
weighted avg       0.75      0.75      0.75     31851

In [27]:
df_basic = df.drop(['height(cm)','weight(kg)','log_gtp'], axis=1)

In [28]:
X,y = df_basic.iloc[:,:-1], df.iloc[:,-1]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size = 0.2, 
                                                    random_state=100,
                                                    stratify=y)

In [30]:
xg_clf = xgb.XGBClassifier(objective='binary:logistic', colsample_bytree=0.3, learning_rate=0.1,
                           max_depth=3, alpha=10, n_estimators=10)

In [31]:
# Fit the model to the training data
xg_clf.fit(X_train, y_train)

# Predict on the test set
y_pred = xg_clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Display classification report
print('\nClassification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.73

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.77      0.76     17920
           1       0.70      0.67      0.68     13931

    accuracy                           0.73     31851
   macro avg       0.72      0.72      0.72     31851
weighted avg       0.73      0.73      0.73     31851

In [32]:
X_train.columns

Index(['age', 'waist(cm)', 'bmi', 'eyesight(left)', 'eyesight(right)',
       'is_blind_left', 'is_blind_right', 'systolic', 'relaxation',
       'blood_pressure_level_Elevated', 'blood_pressure_level_Normal',
       'blood_pressure_level_Stage 1 High BP',
       'blood_pressure_level_Stage 2 High BP',
       'blood_pressure_level_Stage 3 High BP (Emergency)',
       'fasting blood sugar', 'Cholesterol', 'triglyceride', 'HDL', 'LDL',
       'hemoglobin', 'serum creatinine', 'AST', 'ALT', 'Gtp', 'dental caries',
       'Urine protein_1', 'Urine protein_2', 'Urine protein_3',
       'Urine protein_4', 'Urine protein_5', 'Urine protein_6'],
      dtype='object')

# Submission

In [35]:
sub = pd.read_csv(f'../data/test.csv')
sub.head()

,id,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,...,triglyceride,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries
0,159256,40,165,70,84.0,1.2,1.2,1,1,130,...,186,49,115,14.2,1,0.9,19,25,32,0
1,159257,80,160,60,93.0,1.0,1.0,2,2,144,...,158,35,104,13.0,1,1.1,20,12,24,0
2,159258,60,170,70,86.5,0.6,0.7,1,1,117,...,173,39,88,15.4,1,1.4,38,60,36,0
3,159259,40,160,50,67.0,0.3,0.4,1,1,116,...,47,75,128,14.5,1,0.6,25,18,10,1
4,159260,40,170,75,89.4,1.0,0.9,1,1,132,...,100,39,123,16.5,1,1.0,30,39,27,1

In [34]:
import numpy as np
sub['bmi'] = (sub['weight(kg)']/(sub['height(cm)']/100)**2)
sub['is_blind_left'] = np.where(sub['eyesight(left)'] == 9.9, 1, 0)
sub['is_blind_right'] = np.where(sub['eyesight(right)'] == 9.9, 1, 0)
df['blood_pressure_level'] = df.apply(categorize_blood_pressure, axis=1)
sub.head()

NameError: name 'np' is not defined

In [36]:
# Function to categorize blood pressure
def categorize_blood_pressure(row):
    if row['systolic'] < 120 and row['relaxation'] < 80:
        return 'Normal'
    elif 120 <= row['systolic'] <= 129 or 80 <= row['relaxation'] <= 89:
        return 'Elevated'
    elif 130 <= row['systolic'] <= 139 or 90 <= row['relaxation'] <= 99:
        return 'Stage 1 High BP'
    elif 140 <= row['systolic'] <= 179 or 100 <= row['relaxation'] <= 119:
        return 'Stage 2 High BP'
    elif row['systolic'] >= 180 or row['relaxation'] >= 120:
        return 'Stage 3 High BP (Emergency)'
    else:
        return 'Uncategorized'